# Data Cleaning - Noisy Data

## Clustering: Unsupervised learning - K-means algoirthm

**Question**

Give the following data: 13,15,16,16,19,20,20,21,22,22,25,25,25,25,30,33,33,35,35,35,35,36,40,45,46,52,70.<br/>
Apply K-means clustering algoirthm to smooth the data, where k = 3.



In [1]:
import numpy as np
from sklearn.cluster import KMeans

In [2]:
random_state = 2**16
np.random.seed(random_state)

In [3]:
X = np.array([13,15,16,16,19,20,20,21,22,22,25,25,25,25,30,33,33,35,35,35,35,36,40,45,46,52,70])
# sklearn model will think this is one sample with 27 attributes.
print('Before:', X.shape)

# Expand the dimension, so we can have a 27x1 matrix (27 samples, each sample has 1 attribute).
X = np.expand_dims(X, axis=1)
print('After:', X.shape)
print('Print the top 5 data points:')
print(X[:5])

Before: (27,)
After: (27, 1)
Print the top 5 data points:
[[13]
 [15]
 [16]
 [16]
 [19]]


In [4]:
kmean = KMeans(n_clusters=3, random_state=random_state)
kmean.fit(X)

KMeans(n_clusters=3, random_state=65536)

In [5]:
# Note: the clusters are not ordered.
pred = kmean.predict(X)
pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1])

In [6]:
# Compute mean for each cluster
means = np.zeros(3, dtype=np.int32)
for i in range(3):
    idx = np.where(pred == i)[0]
    mean = X[idx].mean()
    means[i] = np.round(mean, decimals=0)

means

array([37, 61, 20])

In [7]:
# Map x with its cluster mean value
X_smoothed = np.array([means[x] for x in pred])

X_smoothed

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 37, 37, 37,
       37, 37, 37, 37, 37, 37, 37, 37, 61, 61])

# Imbalanced Data

## Generating data using SMOTE - Synthetic Minority Over-sampling Technique

<img src="imgs/smote.png" style="height:300px;">

The algorithm of SMOTE:<br/>
<img src="imgs/smote_algorithm.png" style="width:800px;"><br/>
Source: Chawla, N. V., Bowyer, K. W., Hall, L. O., & Kegelmeyer, W. P. (2002). SMOTE: synthetic minority over-sampling technique. Journal of artificial intelligence research, 16, 321-357.

In [8]:
from sklearn.neighbors import KDTree

In [9]:
def smote(X, p, k):
    """ Apply minority over-sampling technique - SMOTE

    Parameters
    ----------
    X : ndarray
        the samples with a minority class.
    p : float
        Amount of SMOTE. If p is less than 1, then the synthetic data will generate from p percent of randomized X.
    k : int
        Number of nearest neighbours.

    Returns
    -------
    outputs : ndarray
        Synthetic minority class samples
    """
    n_X = len(X)
    n_out = int(n_X * p)
    n_attributes = X.shape[1]
    # randomly choose n_X samples from X with replacement.
    indices_outputs = np.random.choice(n_X, size=n_out, replace=True)
    outputs = X.copy()[indices_outputs]

    # Find k nearest neighbours for all X. 
    tree = KDTree(X)
    k_indices = tree.query(X, k=k, return_distance=False)

    for i, i_x in enumerate(indices_outputs):
        nn = np.random.choice(k_indices[i_x], 1)
        dif = X[i_x] - X[nn]
        gap = np.random.rand()
        outputs[i] = X[nn] + gap * dif
    
    return outputs

## Testing SMOTE

In [10]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [11]:
X, y = datasets.load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=random_state)

# Select all sample where class = 0
indices = np.where(y_train==0)[0]
X0 = X_train[indices]

print(X0.shape)

print(X0[:5])

(36, 4)
[[5.4 3.9 1.3 0.4]
 [4.8 3.4 1.9 0.2]
 [5.1 3.4 1.5 0.2]
 [4.9 3.  1.4 0.2]
 [4.4 2.9 1.4 0.2]]


In [12]:
rf = RandomForestClassifier(n_estimators=10, max_depth=5)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, n_estimators=10)

In [13]:
acc_train = rf.score(X_train, y_train)
print('Accuracy on training set: {:2.2%}\n'.format(acc_train))
acc_test = rf.score(X_test, y_test)
print('Accuracy on test set: {:2.2%}\n'.format(acc_test))

Accuracy on training set: 99.05%

Accuracy on test set: 97.78%



In [14]:
X0_smote = smote(X0, 2.0, 5)

print(X0_smote.shape)

print(X0_smote[:10])

pred = rf.predict(X0_smote)
print(pred)

(72, 4)
[[5.20852699 3.50852699 1.5        0.2       ]
 [5.16204993 3.46204993 1.5        0.2       ]
 [5.7        3.93459782 1.65513406 0.32243297]
 [4.87495348 3.1        1.52504652 0.12504652]
 [5.37425964 3.89141988 1.71716024 0.4       ]
 [5.1        3.7        1.5        0.4       ]
 [5.17496291 3.77501236 1.57501236 0.2       ]
 [4.93015091 3.53969818 1.43015091 0.13015091]
 [4.4082553  2.85046819 1.3917447  0.2082553 ]
 [4.81117612 3.08882388 1.57764777 0.2       ]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [15]:
X0_smote = smote(X0, 0.5, 3)

print(X0_smote.shape)

print(X0_smote[:10])

pred = rf.predict(X0_smote)
print(pred)

(18, 4)
[[5.4        3.81501458 1.61501458 0.31501458]
 [4.4        3.01930985 1.3        0.2       ]
 [5.1        3.8        1.54839572 0.25160428]
 [5.1        3.8        1.50323009 0.29676991]
 [5.3151677  3.7        1.5        0.2       ]
 [5.7        3.8        1.7        0.3       ]
 [4.9530067  3.6        1.4        0.1530067 ]
 [4.9        3.1        1.5        0.1       ]
 [5.1        3.5        1.4        0.26962305]
 [5.31687644 3.73375288 1.46624712 0.23375288]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [16]:
X0_smote = smote(X0, 1, 1)

print(X0_smote.shape)

print(X0_smote[:10])

pred = rf.predict(X0_smote)
print(pred)

(36, 4)
[[5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.1 1.6 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.6 1.4 0.1]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [4.4 2.9 1.4 0.2]
 [5.1 3.5 1.4 0.2]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
